### PR TITLE
Adding support for parallel file uploads

### LINKED ISSUE #5: Allow parralel file uploads
**Is your feature request related to a problem? Please describe.**
At the moment, s3backup uploads files 1 at a time. This is going to be quite slow, especially the first time a file tree is backed up.

**Describe the solution you'd like**
Some kind of way of configuring how many files you would like to upload at the same time

**Describe alternatives you've considered**

**Additional context**
This issue is NOT for beginners!

### PR DESCRIPTION
**Pull request by ashikjm**
# Description

Adding support for parallel uploading of files. 

Note: There are no more index uploads at intervals. The index upload will happen only at the end.

Fixes #5 

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

- [x] Running/Modifying existing tests

# Checklist:

- [x] My code has been linted (`make lint`)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have rebased my branch to include the latest changes from `master`

### CODE REVIEW

**Comment by dnnrly** [comment]
The code looks good but it's a shame to miss out on uploading the index file regularly. What I'm worried about is that for a large number of files to backup, you will be forever uploading the same files if you don't get to the end of the uploads. Would it be possible to add this?

It doesn't even matter if you upload in batches that are parallel I think. What's the simplest way of implementing it?

And apologies for taking so long to get back to you, I've not got very much spare time in the evenings.

**Comment by ashikjm** [comment]
> And apologies for taking so long to get back to you, I've not got very much spare time in the evenings.

First of all, thank you for reviewing. I can understand totally understand.

> you will be forever uploading the same files if you don't get to the end of the uploads. Would it be possible to add this?

This totally makes sense. I had this bugging me too when I was writing this. I will try to upload the differences in batches which should need only minimal change to the PR. Thanks.

**Comment by ashikjm** [comment]
Hello @dnnrly, I have made the following changes:
- The local files are batched and uploaded batch by batch.
- File uploads within a batch is parallel(concurrecy is configurable).
- Index is uploaded after each batch.

Please review.

**Comment by dnnrly** [comment]
Nice!

I may  take a few days to get to this PR unfortunately as I'm away from  my laptop for the next few days. 😔

**Comment by dnnrly** [comment]
Hi, I'm back - finally. I saw there was a problem with the PR validation so I pushed a change to this repo to make sure all the tests pass and found some linting errors.

https://github.com/dnnrly/s3backup/pull/13/checks?check_run_id=1016626477

Could you run `make deps lint` and fix these, otherwise the release won't work. 😞

**Comment by ashikjm** [comment]
@dnnrly  Sorry for the delay. I have implemented the lint suggestions. The validation should work fine now. Please check and let me know.

**Comment by dnnrly** [comment]
Don't worry about the delay - it's all good.

**Comment by dnnrly** [comment]
You just earned yourself a new Twitter follower, for what it's worth.

**Comment by ashikjm** [comment]
@dnnrly  Thank you! :)

**Pull request merged**
